### ISSUE TITLE
Image placement in figure shortcodes

### ISSUE THREAD

**Issue by steffilazerte** [ropensci-org/blog-guidance#106]
[In the guide](https://blogguide.ropensci.org/technical.html#addimage) it isn't clear how to make images left-aligned and text-wrapped.

For the community call blog post I tried `class = "pull-left"`, for example:
```
{{< figure src = "julia-silge.jpg" width = "200" alt = "Julia Silge headshot" class = "pull-left">}}
```
And while this left aligned the image, it did not wrap the text.

In the end I reverted to `<img>` tags and styling from previous posts which worked:
```
<img src="/img/blog-images/2020-03-04-commcall-mar2020/julia-silge.jpg" alt="Julia Silge headshot" style="margin: 0px 20px; width: 200px;" align="left">
```

Is it possible to get left-aligned text-wrapped images using shortcodes?

**Comment by maelle** [comment]
the shortcode for that in the new website design is imgtxt.

**Comment by stefaniebutland** [comment]
@steffilazerte assigning you to update this when the new website it launched, please and thanks.

**Comment by stefaniebutland** [comment]
An example use in roweb3 that aligns Mara's headshot to left of text in [blog post](https://roweb3-hugo.netlify.app/blog/2017/11/10/rprofile-mara-averick/):

```
{{< imgtxt src="/img/blog-images/2017-11-10-rprofile-mara-averick/mara_averick.png" alt="Mara Averick, Data Nerd At Large" caption="Mara Averick, Data Nerd At Large">}}

Mara Averick is a non-profit data nerd, blah blah blah

{{< /imgtxt >}}
```

But how would we do equivalent of `class = "pull-right"`? (Opened [issue in roweb3](https://github.com/rosadmin/roweb3/issues/246) private dev repo)

**Comment by maelle** [comment]
It now exists

```
{{< imgtxt side="right" src="/img/blog-images/2017-11-10-rprofile-mara-averick/mara_averick.png" alt="Mara Averick, Data Nerd At Large" caption="Mara Averick, Data Nerd At Large">}}

Mara Averick is a non-profit data nerd, blah blah blah

{{< /imgtxt >}}
```

(side is left by default). Note that text will be _wrapped_ around the image.

**Comment by stefaniebutland** [comment]
@maelle THANK YOU SO MUCH FOR **MORE** TAKING CARE OF US!. I came here to add the example you had already added. 

Ok, less about "taking care/mothering" and more about doing such a careful and complete job with exquisite attention to detail. I'm always learning from the example you set.

**Comment by maelle** [comment]
Mmmh so let me change my mind

* the imgtxt stuff still works. It's good when you want to control what text exactly is wrapped.

* there is also pull-left and pull right as before (well it works _now_, it did not a few minutes ago). I think it's the best thing to advertise for authors.

**Comment by stefaniebutland** [comment]
note from Maëlle on roweb3 
> you either have to use space around equal signs or no space, i.e. no mix? I'd recommend no space.

After website launch Steffi to find out & write all details on adding/ formatting images
