### ISSUE TITLE
Make parallel headings sound similar

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/blog-guidance#129]
In:
2.2 Start the post from a template
2.2.1 Use any template with blogdown’s New Post Addin
2.2.2 Get R Markdown or Markdown template manually

Headings 2.2.1 and 2.2.2 should sound similar since they are different approaches to achieve same thing.

I suggest
2.2.1 Get R Markdown or Markdown template with blogdown’s New Post Addin
2.2.2 Get R Markdown or Markdown template manually

@maelle do you agree? or am I missing something?

**Comment by maelle** [comment]
the addin does a bit more than opening the template but it's hard to find the write word, so I'll do the change.
