### ISSUE TITLE
Find out how to remove figure captions

### ISSUE THREAD

**Issue by maelle** [ropensci-org/blog-guidance#13]
for screenshots, without removing alt text. (not sure it's even possible?!)

**Comment by maelle** [comment]
https://github.com/rstudio/bookdown/issues/856

**Comment by maelle** [comment]
It works but I just hope to remove the hack for something better one day.

**Comment by cderv** [comment]
As explain in https://github.com/rstudio/bookdown/issues/856 **knitr** supports now a `fig.alt` chunk option. It should work as expected for HTML output by creating an `alt=` attribute different than the caption.

**Comment by maelle** [comment]
Thank you for the follow up @cderv!!
