### ISSUE TITLE
yaml "categories" in blogdown new post addin template

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/blog-guidance#130]
Need to update?
On Apr 6, 2020, made new .md post from RStudio blogdown addin and YAML `categories: []` was still there.

![Screen Shot 2020-04-06 at 10 08 38 PM](https://user-images.githubusercontent.com/11927811/78632338-9a072680-7853-11ea-8101-8b963f4351ef.png)

**Comment by maelle** [comment]
oh yeah it is still there and I can't fix it (without making our own addin or something like that), but it's fine, because it's just ignored by Hugo.

**Comment by maelle** [comment]
See e.g. https://github.com/ropensci/roweb2/pull/654/

**Comment by maelle** [comment]
In the list under the addin screenshot there's "Ignore Categories." How do we make clearer that it should also be ignored in the file? We sadly can't keep comments in the Markdown file after it was filled by the addin (this is a limitation of the YAML standard IIRC)

**Comment by maelle** [comment]
:wave: @stefaniebutland, friendly reminder about the question above.
