### ISSUE TITLE
Update the Hugo building instructions

### ISSUE THREAD

**Issue by maelle** [ropensci-org/blog-guidance#134]
https://github.com/r-lib/hugodown/

* Change output in Rmd archetype.
* Tell contributors to install hugodown if they want to contribute a post from Rmd.

Contra: a package to install.
Pro: no more "there will be an index.html, ignore that" since only a index.md will be produced!

**Comment by steffilazerte** [comment]
@maelle, I'm just going through some of the older issues. Is this still relevant?

**Comment by maelle** [comment]
I'd like to keep this issue opened but I've changed my mind on what's the goal.

One thing I'd like us to have is a command contributors can run if they want to build the website locally with our Hugo version. Especially important if they have another Hugo version for their own website.

* In hugodown it means running `hugodown::hugo_install()` with the version number from our Netlify config, then `hugodown::hugo_start()` will use it. 
* We can't recommend blogdown yet because of https://github.com/rstudio/blogdown/issues/611 Once that issue is solved we can recommend `blogdown::build_site()`. I'll update things here when it's possible.

**Comment by maelle** [comment]
@steffilazerte see [`c99291a` (#182)](https://github.com/ropensci-org/blog-guidance/pull/182/commits/c99291a55c794d319c3a73d74c96839026a0b94e)
