### ISSUE TITLE
proper image sizing requires height setting

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/blog-guidance#141]
In new website if you don't set `height`, the `width` does not control image size. Need to update blog guide after website launch.

`{{< figure src = "/img/team/mark-padgham.jpg" width = "250" height = "250" alt = "Headshot of Mark Padgham" >}}`

to address: does this mean an author has to correctly add proportional height if an image is not square?

**Comment by maelle** [comment]
no longer, pfiew
