### ISSUE TITLE
fix or replace twitter card example with YAML twitterImg 

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/blog-guidance#148]
This tweet example no longer shows the specified `twitterImg`. Replace example and use screenshot instead of embedded tweet so we won't have to update again.

![Screen Shot 2020-09-29 at 1 02 47 PM](https://user-images.githubusercontent.com/11927811/94609769-181d1680-0254-11eb-96ba-c77870538c38.png)

**Comment by maelle** [comment]
ah right it seems R Weekly shortlinks expire. I first thought it meant the twitterImg Hugo layout was broken :cold_sweat:
