### ISSUE TITLE
change heading sizes in blogdown addin templates

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/blog-guidance#149]
to fit roweb3 design

there might be other things to check in the templates

**Comment by maelle** [comment]
I changed the heading sizes in https://github.com/ropensci/roweb3/tree/master/archetypes -- good catch, sorry.

@steffilazerte if I follow correctly your tests should encover other issues? otherwise I could have a look some day next week.

**Comment by steffilazerte** [comment]
I was looking specifically for how to format images, but I do plan to look a bit more carefully to see if I can't find any other issues (right at @stefaniebutland?)

**Comment by stefaniebutland** [comment]
Yes please @steffilazerte, including going through & addressing where possible all open issues, especially recent ones Maëlle has opened.
