### ISSUE TITLE
Add link to GH repo in the top navbar

### ISSUE THREAD

**Issue by Bisaloo** [ropensci-org/blog-guidance#151]
I was looking for the repo for this book and I instinctively looked at the GH icon in the top navbar, like the one [in the devguide](https://devguide.ropensci.org/). It's missing here and instead, there is a broken facebook icon.

**Comment by maelle** [comment]
I use the wrong issue number in https://github.com/ropensci-org/blog-guidance/commit/e21e73628be78ea98ad4f0f6aac5fb8e1310dbcf

Thank you!!
