### ISSUE TITLE
`author-file-template.md` in "hidden" details

### ISSUE THREAD

**Issue by Bisaloo** [ropensci-org/blog-guidance#152]
![image](https://user-images.githubusercontent.com/10783929/95190689-00074300-07d0-11eb-9831-49445bef74a8.png)

It took me some time to figure out I could click on it to get the content of `author-file-template.md`. This kind of expandable content is usually marked with a triangle at the beginning, as illustrated in the example below.

<details>
Details code blocks usually start with a triangle
<summary>
Details/summary example
</summary>
</details>

It looks like this might require a change in the function `show_template()` so feel free to move this issue if it is defined in another repo.

**Comment by maelle** [comment]
oooh @Bisaloo actually do you remember I got this very same issue with pkgdown a while back? And _you_ helped? https://github.com/r-lib/pkgdown/issues/884 :grin:

I'll see how to fix things on our end. Good catch in any case!

**Comment by maelle** [comment]
It might be worth an issue in bookdown too :thinking:
