### ISSUE TITLE
Consider using simpler, shorter headings

### ISSUE THREAD

**Issue by steffilazerte** [ropensci-org/blog-guidance#155]
Some headings in the blog guide are long enough that they're cut off, and, to me, not always intuitive. I think some could be simplified and shorted.

For example: 
- "Fork the repo and create your post folder" -> "Getting started" OR "Fork the repository"
- "Start the post from a template" -> "Start the post" OR "Post from template"
- "Walkthrough with code snippets" -> "How-to" OR "Adding content" OR "Adding special content"
- "Create or update your author file" -> "Author files"

**Comment by stefaniebutland** [comment]
fyi @maelle, Steffi and I agreed she would make and refine some proposals for this and we can discuss/review/agree.

She'll ping us when ready for consideration

**Comment by maelle** [comment]
Awesome!

**Comment by steffilazerte** [comment]
Okay! I think the blog guide would benefit from short and punchy headings that are less conversational and more explicit.

I've been pretty brutal and have offered a suggestion for nearly everything. Sometimes my suggestion is more about making the title short that super explicit, but I think that long and explicit is usually worse.

At the bottom I also have some suggestions for reorganizing a couple of sections. Let me know if you think it would be simpler for me to make this a document in a new branch that you could directly edit with suggestions.

Original                      | New
------------------------------|-----------------------------------
1.2 Themes of posts           | 1.2 Themes
1.3 What goes in your post?   | 1.3 Post content
2.1 Fork the repo and ...     | 2.1 Fork `roweb3`  **OR** Fork the repository **OR** Getting started
2.2 Start the post from a ... | 2.2 Post template
2.3 Walkthrough with code ... | 2.3 Adding content
2.3.1 What goes in YAML       | 2.3.1 YAML
2.3.3 To add an image         | 2.3.3 External images
2.3.4 To add a figure ...     | 2.3.4 Rmd-created images
2.3.5 To add a citation       | 2.3.5 Citations
2.3.6 To embed a tweet        | 2.3.6 Embedded tweets
2.5 Create or update your ... | 2.5 Author files
2.7 Submit your draft post    | 2.7 Submit post **OR** Submit draft **OR** Submit draft post
3 Responding to Editor's ...  | 3 Respond to review **OR** Respond to feedback
A Post template in Markdown   | A Template - Post (md)
B Post template in R Markdown | B Template - Post (Rmd)
C Author file template        | C Template - Author file
D Author checklist for a ...  | D Author Checklist - Posts on peer-reviewed packages *
E Author checklist for any... | E Author Checklist - Other posts *
F Editor checklist for a ...  | F Editor checklist - Posts on peer-reviewed packages *
G Editor checklist for any... | G Editor checklist - Other posts *
H Understanding Twitter cards | H Twitter cards


\* These would be updated in several different spots (2.6 Presubmission checks, 5.1 Review a post, and Appendix)

**Other organizational suggestions**

- Move 2.3.2 "Examples" to the end of the section (so it would be come 2.3.6)
- Move 2.5 "Create or update your author file" to 2.2 (i.e right before "Start the post from a template")

**Comment by maelle** [comment]
the new headings look good to me! It'll be more important to check cross-references aren't broken.
