### ISSUE TITLE
Twitter card links

### ISSUE THREAD

**Issue by steffilazerte** [ropensci-org/blog-guidance#169]
Right now the blog guide suggests using the image path of:
`blog/2019/06/04/post-template/name-of-image.png`

But in a recent technote (https://github.com/ropensci/roweb3/pull/122) the only path that worked was:
`technotes/2021-02-03-targets/card.png`

Is this the new standard? Should we update the blog guide accordingly?

(@maelle I think this is a question for you :grin:)

**Comment by maelle** [comment]
yes! I think I got confused with page bundles, sorry!!

**Comment by stefaniebutland** [comment]
I used `twitterImg: blog/2021/02/02/ropensci-community-calls/commcalls-img.png` successfully today in the validator

**Comment by steffilazerte** [comment]
So weird! We should see if one version is more reliable than the other and use that in the dev guide...

**Comment by maelle** [comment]
Sooo I think the confusion comes from posts being in leaf bundles or not, and where the images live.

As we recommend using bundles we should recommend the form `blog/2019/06/04/post-template/name-of-image.png`.

To find where the image lives in the post preview one can right-click on an image and get its address.

**Comment by steffilazerte** [comment]
I think this is good to close as this is what we have.
