### ISSUE TITLE
 sample messages for authors and reviewers

### ISSUE THREAD

**Issue by maelle** [ropensci-org/blog-guidance#17]
can be included just like other templates :-)

**Comment by stefaniebutland** [comment]
The idea for these sample messages is like dev guide or [JOSS guide](https://joss.readthedocs.io/en/latest/editing.html#message-to-authors-at-the-end-of-a-review)

**Comment by stefaniebutland** [comment]
moving to "nice to have" milestone.

Editor guide ch5 has a list of things to include in review message to author.

**Comment by steffilazerte** [comment]
I don't think this is necessary. Closing, but feel free to re-open if you feel strongly :grin:
