### ISSUE TITLE
add guidance about image sizes

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/blog-guidance#171]
See Big images issue https://github.com/ropensci/roweb3/issues/6 for suggestion and solution

**Comment by steffilazerte** [comment]
I'll also add a reference to https://bookdown.org/yihui/rmarkdown-cookbook/optipng.html cf (#166)

**Comment by maelle** [comment]
There's also https://github.com/ardata-fr/minimage by @davidgohel (still experimental, but should be useful later)

I like the ease of use of websites such as tinyPNG but I think using a local tool is probably better?
