### ISSUE TITLE
Backticks for software name?

### ISSUE THREAD

**Issue by maelle** [ropensci-org/blog-guidance#184]
We have https://blogguide.ropensci.org/technical.html#styleguide

But @noamross has a different opinion https://github.com/ropensci/roweb3/pull/291#discussion_r743606724

I have gotten used to not using special formatting but would like to hear others' opinions in particular from the blog editors @stefaniebutland @steffilazerte

**Comment by noamross** [comment]
If we already have guidance (which I wasn't aware of, thanks!), let's just go with that.

**Comment by maelle** [comment]
Ok then!

(Of course we have guides for all the things! :stuck_out_tongue_winking_eye:)
