### ISSUE TITLE
Do we need an ropensci.org subdomain for this?

### ISSUE THREAD

**Issue by maelle** [ropensci-org/blog-guidance#19]
blogguide.ropensci.org or sthg like that?

**Comment by stefaniebutland** [comment]
yes please to blogguide.ropensci.org

**Comment by stefaniebutland** [comment]
@maelle, Karthik said "I need to know more about where it is set up and what I am pointing the DNS to."

Can you please arrange the setup with him?

**Comment by stefaniebutland** [comment]
@maelle you can choose the milestone for this one
