### ISSUE TITLE
Switch to Quarto

### ISSUE THREAD

**Issue by maelle** [ropensci-org/blog-guidance#196]
See how nice https://devdevguide.netlify.app/ is!

If both of you @steffilazerte and @yabellini agree, I can make a PR updating this guidance to Quarto. :smile_cat:

**Comment by steffilazerte** [comment]
You mean updating the blog guide to explain how to knit with Quarto? In addtion to the `blogdown` instructions? I think that makes sense, Quarto is only going to get more popular afterall!

**Comment by maelle** [comment]
No I mean this guidance book would be built with Quarto instead of bookdown. But let me open an issue about your good idea as well!

**Comment by maelle** [comment]
Look who wrote this guidance https://www.openscapes.org/blog/2022/07/21/quarto-migrate/ :grin:

**Comment by maelle** [comment]
@yabellini depending on your decision next week I can either transform this repo or close the issue. :innocent:

**Comment by yabellini** [comment]
Hey thanks for waiting for me!
I think switch to Quarto with this guide Is a good opportunity to learn the framework.

So, a yes from my side.

**Comment by maelle** [comment]
Done!
