### ISSUE TITLE
Twitter card validator doesn't work with any blog posts

### ISSUE THREAD

**Issue by steffilazerte** [ropensci-org/blog-guidance#199]
The [Twitter card validator](https://cards-dev.twitter.com/validator) we recommend for checking out Twitter cards doesn't seem to be working for any blog posts (not only previews).

For example, I get "Unable to render Card preview" on both Firefox and Chrome for https://ropensci.org/blog/2021/01/19/introducing-baseset/ (which I think gets the default rOpenSci card) and https://ropensci.org/blog/2022/03/29/rsnps-update/ (which has a custom Twitter card).

But the log (for the second) says 
```
INFO:  Page fetched successfully
INFO:  13 metatags were found
INFO:  twitter:card = summary_large_image tag found
INFO:  Card loaded successfully
```

@maelle any ideas? Right now I find it better to draft a tweet with the URL (but I'm not sure it works with the preview)...

**Comment by steffilazerte** [comment]
Or is this an issue for `roweb3`?

**Comment by maelle** [comment]
Oh weird! 
- The cards still look good on Twitter itself, right?
- If I paste URLs into a Slack message to myself I see a card.
Still exploring. :detective:

**Comment by maelle** [comment]
https://twittercommunity.com/t/unable-to-render-card-preview/173566

**Comment by maelle** [comment]
So I'd say we just wait for now!

Drafting a tweet (as you said) / posting in a Slack message to yourself is the workaround in the meantime.

**Comment by steffilazerte** [comment]
Huh, I should have thought to check Twitter. Let's leave this issue open. If Twitter doesn't fix the card validator, we should update the Blog Guide instructions.

**Comment by yabellini** [comment]
Perhaps remove the mention of Twitter card validator now.

**Comment by steffilazerte** [comment]
Yes, I want to update those checklists as well! Moved this to a new issue #220
