### ISSUE TITLE
Add guidance for using qmd if possible

### ISSUE THREAD

**Issue by maelle** [ropensci-org/blog-guidance#200]

**Comment by maelle** [comment]
@steffilazerte @yabellini I tried Quarto in https://github.com/ropensci/roweb3/pull/834

Following https://quarto.org/docs/output-formats/hugo.html

I haven't tried making the code chunks output Hugo figure shortcodes so they create images using `img` tags which is probably fine.

I haven't explored the special highlighting of some code lines because I don't think we ever use it anyway?

Did anyone ever ask you for a Quarto template?

Unless you're against it I think we can merge the archetype (I'll create it from my qmd post example) as it should be ok for what most people need to do?

**Comment by steffilazerte** [comment]
I don't think anyone has asked for a Quarto template (possibly once at most?), and I've never seen anyone use code highlighting. I made a couple of suggestions to your archetype PR to standardize the language with the extension, but other than that I think it's good to go!
