### ISSUE TITLE
Update checklists

### ISSUE THREAD

**Issue by steffilazerte** [ropensci-org/blog-guidance#220]
@yabellini, @maelle, any thoughts? These are the items I'm thinking of adding

- [ ] Remove references to Twitter
- [ ] Add/specify language specific items?
  - e.g., title capitalization is for English only

**Comment by steffilazerte** [comment]
Yes, I can add the checklist tweaks to that PR too, if you don't mind, so we have just one PR with little fiddly stuff :grin:

**Comment by yabellini** [comment]
@steffilazerte I realized I was talking about the contributing guide, not the blog guide! I will add a PR to the other book, not this one. So, please, don't wait for me here. Sorry for the confusion!

**Comment by steffilazerte** [comment]
No worries! 👍🏼

**Comment by maelle** [comment]
@steffilazerte you mean removing references to Twitter in any new blog post?

**Comment by steffilazerte** [comment]
No, in the checklist there is an item for the Twitter validator that is obsolete (which is what I was referring to). Although perhaps the twitter card YAML key should be revisited too...?

**Comment by maelle** [comment]
https://github.com/ropensci/roweb3/issues/590

**Comment by maelle** [comment]
@steffilazerte you could push this to the PR that adds the editor field? #230

**Comment by yabellini** [comment]
I did a lot fo changes here to remove twitter from the guide: https://github.com/ropensci-org/blog-guidance/pull/229

**Comment by steffilazerte** [comment]
I'll add it to Yani's today or tomorrow 😁

**Comment by steffilazerte** [comment]
I think we're good here
