### ISSUE TITLE
Pick a better 'preface' example

### ISSUE THREAD

**Issue by steffilazerte** [ropensci-org/blog-guidance#222]
This refers to using the preface for a different language (but we don't do that anymore), do we have another, better example?
https://github.com/ropensci-org/blog-guidance/blob/3afe965adc2d046c6e4a9c4a6bc2e84645c397c6/authortechnical.Rmd#L142

**Comment by steffilazerte** [comment]
Perhaps this one: https://ropensci.org/blog/2023/04/04/waywiser-is-now-a-part-of-ropensci/

**Comment by yabellini** [comment]
I like this example :-)

**Comment by maelle** [comment]
The problem is that we have a special yaml field for crossposts so that example above doesn't use the preface yaml field I think (or similar posts shouldn't use the preface yaml field). I'd suggest a post from the Rprofile series like https://ropensci.org/blog/2018/06/08/rprofile-julia-silge/

**Comment by yabellini** [comment]
Oh, you are right! I like the example.

**Comment by steffilazerte** [comment]
Agreed, looks good!
