### ISSUE TITLE
How do people find these guidelines

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/blog-guidance#24]
- add link to book in software review editors' checklist
- Scott suggested putting link in example pull request

**Comment by stefaniebutland** [comment]
roweb2 readme now links to book https://github.com/ropensci/roweb2/blob/master/readme.md

Revise that text after "official" release i.e. we're pretty confident no errors

**Comment by maelle** [comment]
Can this be closed? 

"Scott suggested putting link in example pull request" which example PR?

**Comment by stefaniebutland** [comment]
> which example PR?

maybe the one you used to have for a bundled post example?
