### ISSUE TITLE
Is discuss forum entry auto-created for a post?

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/blog-guidance#30]
Ask Scott if he can implement this so editor doesn't have to

**Comment by maelle** [comment]
On @sckott's todo list :-)

**Comment by sckott** [comment]
yep

**Comment by stefaniebutland** [comment]
I'll give Scott a heads-up when the next post is cooking so he can test this

**Comment by stefaniebutland** [comment]
@sckott What text will you use to auto-create blog topic in discourse forum?

Maëlle has added a YAML `description` tag in post template for people to add a short post summary. Will that be helpful? i.e. would you use that if it was there?

Trying to decide how long to recommend people make their description

**Comment by sckott** [comment]
The Discourse software just puts a blob in for you of the first part of the post

**Comment by stefaniebutland** [comment]
@sckott what number of characters does is use?

**Comment by sckott** [comment]
here's an example https://discuss.ropensci.org/t/release-mongolite-1-0/626 and see any of those early blog posts

**Comment by stefaniebutland** [comment]
From Scott:

we don’t want discourse threads opened for older posts, like 2014 era, - so we need to either set for newer posts something like `topicid: FALSE`  so in the hugo code we can just not use discourse embed code if `topicid` is missing, if there is a `topicid` with a number then we just embed that number, and if `topicid: FALSE`  then we do the automatic thread open thing

**Comment by maelle** [comment]
In the Hugo code you could also filter by year. Or one could edit the YAML metadata of older posts. I think it's preferrable to `topicid: FALSE` because that'd need explaining for authors.

**Comment by sckott** [comment]
i'm confused @maelle - you want to do `topicid: FALSE` OR you want to avoid that?

**Comment by maelle** [comment]
I want to avoid it. I prefer modifying the old posts' metadata (which I've done in the past for e.g. cleaning tags).

**Comment by sckott** [comment]
ok, sounds good to me

**Comment by maelle** [comment]
you'll just have to tell me what to add to the old posts, and what "old" is. :-)

**Comment by sckott** [comment]
> what "old" is

I'd think a rule that has two paprts:

1. posts before the year 2020, and 
2. anything that doesn't have a topicid entry

if we do get this automatic post to work, then new posts won't have a topicid, but they'll be newer than 2020

**Comment by stefaniebutland** [comment]
y'all can note that this issue is for next milestone, but I DO appreciate your action.

**Comment by maelle** [comment]
(still commenting before I forget :wink:)

I was thinking that if we end up not liking the built-in automatic posting from Discuss we could still make our own workflow with GH actions + the Discourse API (when merging a PR with a given word in the commit message for instance).

**Comment by sckott** [comment]
true

**Comment by stefaniebutland** [comment]
Scott will test this on dummy posts, aiming to implement for next milestone if possible.

**Comment by stefaniebutland** [comment]
Edit Editor Guide - [Publish a Post ](https://blogguide.ropensci.org/editor.html#publish) after Scott is done

**Comment by sckott** [comment]
In the **Publish a post section**, could replace the paragraph starting with _Editor adds the YAML ..._ and instead say

> A `topic` linked to the blog post will automatically be created in the [discussion forum blogs category](https://discuss.ropensci.org/c/blog/) posts both on the regular blog and technotes. 

may also want to add a note somewhere about older posts in case someone is editing older posts or fixing them

> Note about older posts: Very old posts from (before March 2017) have no comments at all; these posts have no `topicid` field in their yaml header. Newer posts (March 2017 onward) have a yaml field `topicid` and a number in it that links to a topic that we manually created in the forum. Posts newer than March 9, 2020 won't have a `topicid` field in their yaml header as a forum topic is automatically created.
