### ISSUE TITLE
Gifs in tweets

### ISSUE THREAD

**Issue by maelle** [ropensci-org/blog-guidance#36]
What's our guidance reg gifs?

My proposal
* One can include a gif that was created for the post (e.g. an animated plot)
* But not a Giphy gif since it might be interpreted differently by people who know more/less context about the gif thing (e.g. the TV show)
* When using gif we should add their description at the bottom of the tweet cf https://www.a11ywithlindsey.com/blog/7-ways-tweets-more-accessible `[Gif alt: descriptive phrase]`

**Comment by stefaniebutland** [comment]
added, with minor edits, to https://github.com/ropensci-org/blog-guidance/pull/46
