### ISSUE TITLE
make it less scary for post authors

### ISSUE THREAD

**Issue by maelle** [ropensci-org/blog-guidance#38]
Thanks @richfitz for the suggestions

* Add one quickstart by chapter (cf https://github.com/ropensci-org/blog-guidance/pull/41 for how-to)

* Add a message at the beginning stating the guide is there to _help_ authors (and that our actual "rules" are not that many?)

**Comment by richfitz** [comment]
Further, you might separate the guide (or the information in the guide) into sections:

* these are things we require that you do (such as create an author file)
* this is information to help you (such as how to embed a tweet)

But the information might grade between the two so this might be hard in practice.

However, you might consider a list of "this is the minimum you have to do for us to engage in helping you" with the implication being the rest is things that the editors would be ok to help with getting people to meet

**Comment by stefaniebutland** [comment]
addressed in #116. Listed chapters content and noted required reading 
good enough for now I think
