### ISSUE TITLE
Consolidate list of posts in content guidelines and hide it by default

### ISSUE THREAD

**Issue by maelle** [ropensci-org/blog-guidance#39]
* At the moment there are two lists of post, wouldn't one be enough?

* Hide it by default or put it at the bottom?

**Comment by stefaniebutland** [comment]
consolidated in https://github.com/ropensci-org/blog-guidance/pull/69

> Hide it by default or put it at the bottom?

ok as is for now.
Ideally, list types of posts and expand the examples below each type.

- About a peer-reviewed package developed by the authors
  - ➡️  expand list
- Major updates to key packages
  - ➡️  expand list
- etc
