### ISSUE TITLE
Broken link to Rmd template

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/blog-guidance#45]
In https://ropensci-blog-guidance.netlify.com/templatermd.html

'R Markdown template' is linked to https://github.com/rosadmin/blog-guidance/blob/master/templates/author-file-template.Rmd and needs to link to roblog I think

**Comment by maelle** [comment]
Oops good catch, can you please change the link to https://github.com/ropensci-org/blog-guidance/blob/master/templates/post-template.Rmd? Thanks!
