### ISSUE TITLE
Add book cover

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/blog-guidance#61]

**Comment by stefaniebutland** [comment]
(yes, kidding...but maybe I can stage something 😉 )
![IMG_6283](https://user-images.githubusercontent.com/11927811/74180734-dff99280-4bf4-11ea-90e7-d5bd5f1e7bf9.png)

**Comment by stefaniebutland** [comment]
examples
https://www.pexels.com/photo/woman-wearing-red-and-black-checkered-blouse-using-macbook-1181472/
https://www.pexels.com/photo/laptop-computer-macbook-apple-7361/

**Comment by maelle** [comment]
Ruby the dog or @sckott's cat looking at the blog on a laptop? 😇

**Comment by stefaniebutland** [comment]
I can arrange this :-)

**Comment by maelle** [comment]
And then the book title and authors should be pasted on the photo. Plus rOpenSci logo.

**Comment by stefaniebutland** [comment]
done
