### ISSUE TITLE
single quotes or double quotes

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/blog-guidance#77]
for things like 

the "Review changes" button

**Comment by stefaniebutland** [comment]
From [Wikipedia](https://en.wikipedia.org/wiki/Quotation_mark#Usage) 
> In American writing, quotation marks are normally the double kind (the primary style). If quotation marks are used inside another pair of quotation marks, then single quotation marks are used. For example: "Didn't she say 'I like red best' when I asked her wine preferences?" 

closing issue

**Comment by maelle** [comment]
Now that's good to know!
