### ISSUE TITLE
Add links to editor checklists

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/blog-guidance#80]
In PR https://github.com/ropensci-org/blog-guidance/pull/78

add links in "Copy and paste either the [editor checklist for a post about a peer-reviewed package]LINK, or the [editor checklist for any other post]LINK, into the box that appears when you click the green “Review changes” button."

**Comment by stefaniebutland** [comment]
done in https://github.com/ropensci-org/blog-guidance/pull/78
will close when I see preview

**Comment by maelle** [comment]
No preview (my fault, I'm exploring why) but I merged and checked the links.
