### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by sckott** [ropensci-org/blog-guidance#86]
really good, just a few comments:

- in setion 1.2 "Themes of posts" you say 

> Read a few blog posts and tech notes and consider what you like (or not) about them

but the link goes to all of the blog posts, maybe link separately to blog post and tech notes?

- in editor guide: _GitHub does not highlight which word(s) where edited._ - i think it should be _were_

**Comment by stefaniebutland** [comment]
thanks Scott. Will make those changes.

**Comment by stefaniebutland** [comment]
addressed in commits March 2
