### ISSUE TITLE
Feedback - References to roblog package

### ISSUE THREAD

**Issue by steffilazerte** [ropensci-org/blog-guidance#95]
The `roblog` package has a couple of broken links and the installation instructions didn't work for me.

**Broken Links** (I would have fixed them, but I'm not sure what they should be)
- [2.2.3 Get any template from the roblog package](https://blogguide.ropensci.org/technical.html#roblogtemplates) 
- [2.6 Pre-submission checks](https://blogguide.ropensci.org/technical.html#presubchecks)
- Also the `roblog` link to the docs on the [GitHub site](https://github.com/ropenscilabs/roblog)

**Installation instructions**
- Didn't work: `install.packages("roblog", repos = "https://dev.ropensci.org")`
- Worked: `remotes::install_github("ropenscilabs/roblog")`

**Comment by maelle** [comment]
The broken links to roblog docs website should be fixed in a few days (I re-added roblog to the registry building).

I think this will solve the roblog installation at the same time.

I'll assign the issue to myself because all the broken stuff is my responsability. :angel:

**Comment by maelle** [comment]
* The broken links are fixed see https://docs.ropensci.org/roblog/ and https://docs.ropensci.org/roblog/articles/checks-guidance.html (the vignette is also more exhaustive than it used to be)

* I fixed the guidance link in roblog README.

* Installation instructions to be fixed via #98 

Thanks @steffilazerte

**Comment by steffilazerte** [comment]
Everything works for me now, thanks!

**Comment by steffilazerte** [comment]
Well actually `install.packages("roblog", repos = "https://dev.ropensci.org")` now works for me. But I see that you changed the instructions to use remotes. Does it matter?

**Comment by maelle** [comment]
I don't think it matters but I might change it again then! Thanks!

**Comment by stefaniebutland** [comment]
can we close this?

**Comment by maelle** [comment]
Yes from me

**Comment by steffilazerte** [comment]
Fine for me too!
