### ISSUE TITLE
Feedback - YAML content

### ISSUE THREAD

**Issue by steffilazerte** [ropensci-org/blog-guidance#97]
In the YAML:

- description: “A very short summary of your post”. 
How short is short? Twitter limits? Or shorter? Perhaps add something like:  “A very short summary of your post (~ 100 characters)"

- twitterImg: blog/2019/06/04/post-template/name-of-image.png 
Is this the correct folder? 
Should it be content/blog/2019-06-04-post-template/name-of-image.png ?
Is this image supposed to show up in the preview of the blog post with https://cards-dev.twitter.com/validator? If so, I cannot for the life of me figure out where to put that image and[ how to reference it in the YAML](https://github.com/steffilazerte/roweb2/blob/fb3a4f25ab2fc7bf8bc0bcbedc104ba7bc0733f6/content/blog/2020-02-28-weathercan-dummy/index.Rmd#L31)

**Comment by maelle** [comment]
It should be blog/yyyy/mm/dd/slug/filename which is what you have in the Rmd in your PR, so if you knit it should work?

I've been confused too in the past, maybe I didn't completely fix it, fingers crossed.

**Comment by steffilazerte** [comment]
:woman_facepalming: I forgot to knit the Rmd to the md ugh! Now it works! Needed to Preview the Card twice though, to get the picture, so that note in the docs is good!

**Comment by maelle** [comment]
Pfiew! 😁

Maybe I should exploee one day why we need to click twice 🤔

**Comment by stefaniebutland** [comment]
in PR #107, changed YAML `description` to add length. `description: "A very short summary of your post (~ 100 characters)"`
