### ISSUE TITLE
Clarify text on opening draft PR?

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/blog-guidance#99]
We say "Open a draft pull request (PR) from your fork (using the web interface, see step 8 for creating a draft), or usethis::pr_push())" in https://blogguide.ropensci.org/technical.html#submitpost

but I don't think `usethis` has option for draft PR. Is that right @maelle? Do we need to clarify our text?

**Comment by maelle** [comment]
I think that since `usethis` opens the PR opening web interface https://usethis.r-lib.org/articles/articles/pr-functions.html#submit-pull-request you could still open a draft PR but I'm going to test it right away.

**Comment by stefaniebutland** [comment]
done
